### ISSUE TITLE
CancelIoEx are not fully implemented on Windows XP.

### ISSUE THREAD

**Issue by lygstate** [Chuyu-Team/YY-Thunks#18]
Any possiblity to implement it properly on XP?

**Comment by zeroclear** [comment]
CancelIoEx calls NtCancelIoFileEx internally, it needs kernel support. YY-Thunks works only at user layer, so I think this is an impossible task.
IO operations complete in kernel, from Vista kernel maintains a cancel IO list, thus CancelIoEx can cancel arbitrary IO request rather than all. Theoretically modify XP kernel can achieve it, but IO is the key of kernel, you can imagine how hard it is.

**Comment by mingkuang-Chuyu** [comment]
no……
This is almost impossible to complete.
Of course, if you have good suggestions, please tell me.

**Comment by mingkuang-Chuyu** [comment]
我是无法解决，如果你可以解决 请提供解决方案……
